package com.orm;

/**
 * TDoc generated by MyEclipse Persistence Tools
 */

public class Tjiandati
{

	// Fields

	private int id;

	private String name;
	
	private String daan;

	private String del;

	public String getDaan()
	{
		return daan;
	}

	public void setDaan(String daan)
	{
		this.daan = daan;
	}

	public String getDel()
	{
		return del;
	}

	public void setDel(String del)
	{
		this.del = del;
	}


	public int getId()
	{
		return id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public String getName()
	{
		return name;
	}

	public void setName(String name)
	{
		this.name = name;
	}


}