package com.orm;

/**
 * TDoc generated by MyEclipse Persistence Tools
 */

public class Tshipin
{

	// Fields

	private String id;

	private String title;
	
	private int catelog_id;
	
	private String catelog_name;
	
	private String content;

	private String fujian;

	private String fujianYuanshiming;
	
	private String shijian;
	
	private String del;

	// Constructors

	/** default constructor */
	public Tshipin()
	{
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}


	public int getCatelog_id() {
		return catelog_id;
	}

	public void setCatelog_id(int catelog_id) {
		this.catelog_id = catelog_id;
	}
	
	

	public String getCatelog_name() {
		return catelog_name;
	}

	public void setCatelog_name(String catelog_name) {
		this.catelog_name = catelog_name;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getFujian() {
		return fujian;
	}

	public void setFujian(String fujian) {
		this.fujian = fujian;
	}

	public String getFujianYuanshiming() {
		return fujianYuanshiming;
	}

	public void setFujianYuanshiming(String fujianYuanshiming) {
		this.fujianYuanshiming = fujianYuanshiming;
	}

	public String getShijian() {
		return shijian;
	}

	public void setShijian(String shijian) {
		this.shijian = shijian;
	}

	public String getDel() {
		return del;
	}

	public void setDel(String del) {
		this.del = del;
	}
	

}